FROM almalinux:9
RUN dnf install nginx -y
LABEL project="expense"
LABEL owner="daws-82s"
LABEL maintainer="daws-82s"
LABEL description="This is a simple nginx server"
LABEL version="1.0"
LABEL release-date="2022-01-01"
